import { Command } from 'commander';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs/promises';
import path from 'path';

/**
 * Initialize configuration command
 */
export function createInitCommand(): Command {
  const command = new Command('init');

  command
    .description('Initialize Job Applier configuration')
    .option('-f, --force', 'Overwrite existing configuration')
    .action(async (options) => {
      console.log(chalk.blue.bold('\n🚀 Job Applier Setup\n'));

      const configPath = path.join(process.cwd(), '.env');

      // Check if config exists
      try {
        await fs.access(configPath);
        if (!options.force) {
          const { overwrite } = await inquirer.prompt([
            {
              type: 'confirm',
              name: 'overwrite',
              message: 'Configuration already exists. Overwrite?',
              default: false,
            },
          ]);
          if (!overwrite) {
            console.log(chalk.yellow('Setup cancelled.'));
            return;
          }
        }
      } catch {
        // File doesn't exist, continue
      }

      // Collect configuration
      const answers = await inquirer.prompt([
        {
          type: 'password',
          name: 'anthropicApiKey',
          message: 'Enter your Claude API key:',
          validate: (input) => input.length > 0 || 'API key is required',
        },
        {
          type: 'password',
          name: 'exaApiKey',
          message: 'Enter your Exa API key:',
          validate: (input) => input.length > 0 || 'API key is required',
        },
        {
          type: 'input',
          name: 'dataDir',
          message: 'Data directory:',
          default: './.job-applier',
        },
        {
          type: 'confirm',
          name: 'headless',
          message: 'Run browser in headless mode?',
          default: false,
        },
        {
          type: 'number',
          name: 'maxApplicationsPerDay',
          message: 'Maximum applications per day:',
          default: 25,
        },
        {
          type: 'number',
          name: 'minDelayBetweenActions',
          message: 'Minimum delay between actions (seconds):',
          default: 2,
        },
        {
          type: 'number',
          name: 'maxDelayBetweenActions',
          message: 'Maximum delay between actions (seconds):',
          default: 5,
          validate: (input, answers) => {
            const minDelay =
              typeof answers.minDelayBetweenActions === 'number'
                ? answers.minDelayBetweenActions
                : Number(answers.minDelayBetweenActions);
            if (!Number.isFinite(minDelay)) {
              return 'Minimum delay must be a number';
            }
            if (!Number.isFinite(input)) {
              return 'Maximum delay must be a number';
            }
            return input >= minDelay || 'Maximum delay must be at least minimum delay';
          },
        },
      ]);

      // Platform credentials
      const { setupPlatforms } = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'setupPlatforms',
          message: 'Set up platform credentials now?',
          default: true,
        },
      ]);

      let linkedinEmail = '';
      let linkedinPassword = '';
      let indeedEmail = '';
      let indeedPassword = '';

      if (setupPlatforms) {
        const platformAnswers = await inquirer.prompt([
          {
            type: 'input',
            name: 'linkedinEmail',
            message: 'LinkedIn email (leave empty to skip):',
          },
          {
            type: 'password',
            name: 'linkedinPassword',
            message: 'LinkedIn password:',
            when: (answers) => answers.linkedinEmail.length > 0,
          },
          {
            type: 'input',
            name: 'indeedEmail',
            message: 'Indeed email (leave empty to skip):',
          },
          {
            type: 'password',
            name: 'indeedPassword',
            message: 'Indeed password:',
            when: (answers) => answers.indeedEmail.length > 0,
          },
        ]);

        linkedinEmail = platformAnswers.linkedinEmail || '';
        linkedinPassword = platformAnswers.linkedinPassword || '';
        indeedEmail = platformAnswers.indeedEmail || '';
        indeedPassword = platformAnswers.indeedPassword || '';
      }

      // Generate .env file
      const spinner = ora('Saving configuration...').start();
      const minDelayMs = Math.round(
        Number(answers.minDelayBetweenActions) * 1000
      );
      const maxDelayMs = Math.round(
        Number(answers.maxDelayBetweenActions) * 1000
      );

      const envContent = `# Job Applier Configuration
# Generated by job-applier init

# Anthropic Claude
ANTHROPIC_API_KEY=${answers.anthropicApiKey}

# Exa Search API
EXA_API_KEY=${answers.exaApiKey}

# Application Settings
DATA_DIR=${answers.dataDir}
BROWSER_HEADLESS=${answers.headless}
MAX_APPLICATIONS_PER_DAY=${answers.maxApplicationsPerDay}
MIN_DELAY_BETWEEN_ACTIONS=${minDelayMs}
MAX_DELAY_BETWEEN_ACTIONS=${maxDelayMs}

# Platform Credentials
LINKEDIN_EMAIL=${linkedinEmail}
LINKEDIN_PASSWORD=${linkedinPassword}
INDEED_EMAIL=${indeedEmail}
INDEED_PASSWORD=${indeedPassword}
`;

      try {
        await fs.writeFile(configPath, envContent);
        spinner.succeed('Configuration saved to .env');

        // Create data directory
        await fs.mkdir(answers.dataDir, { recursive: true });
        console.log(chalk.green(`✓ Created data directory: ${answers.dataDir}`));

        console.log(chalk.green.bold('\n✅ Setup complete!\n'));
        console.log('Next steps:');
        console.log(chalk.cyan('  1. Import your resume: job-applier resume import <path>'));
        console.log(chalk.cyan('  2. Search for jobs: job-applier search "Software Engineer"'));
        console.log(chalk.cyan('  3. Start applying: job-applier apply --auto\n'));
      } catch (error) {
        spinner.fail('Failed to save configuration');
        console.error(chalk.red(error));
      }
    });

  return command;
}
